using Lagrange.Proto;

namespace Lagrange.Core.Internal.Packets.Web;

[ProtoPackable] internal partial class AlbumExtMapEntry { [ProtoMember(1)] public string Key { get; set; } = string.Empty; [ProtoMember(2)] public string Value { get; set; } = string.Empty; }
[ProtoPackable] internal partial class GetMediaListReqInfo { [ProtoMember(1)] public string GroupId { get; set; } = string.Empty; [ProtoMember(2)] public string AlbumId { get; set; } = string.Empty; [ProtoMember(3)] public int Field3 { get; set; } [ProtoMember(4)] public string Field4 { get; set; } = string.Empty; [ProtoMember(5)] public string PageInfo { get; set; } = string.Empty; }
[ProtoPackable] internal partial class GetMediaListRequest { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(2)] public byte[] Field2 { get; set; } = []; [ProtoMember(3)] public byte[] Field3 { get; set; } = []; [ProtoMember(4)] public GetMediaListReqInfo ReqInfo { get; set; } = new(); [ProtoMember(5)] public string TraceId { get; set; } = string.Empty; [ProtoMember(10)] public List<AlbumExtMapEntry> ExtMap { get; set; } = []; }
[ProtoPackable] internal partial class AlbumUrlInfo { [ProtoMember(1)] public string Url { get; set; } = string.Empty; [ProtoMember(2)] public uint Width { get; set; } [ProtoMember(3)] public uint Height { get; set; } }
[ProtoPackable] internal partial class AlbumPhotoUrl { [ProtoMember(1)] public uint Spec { get; set; } [ProtoMember(2)] public AlbumUrlInfo? Url { get; set; } }
[ProtoPackable] internal partial class AlbumImageInfo { [ProtoMember(1)] public string Name { get; set; } = string.Empty; [ProtoMember(2)] public string Sloc { get; set; } = string.Empty; [ProtoMember(3)] public string Lloc { get; set; } = string.Empty; [ProtoMember(4)] public List<AlbumPhotoUrl> PhotoUrls { get; set; } = []; [ProtoMember(5)] public AlbumUrlInfo? DefaultUrl { get; set; } [ProtoMember(6)] public bool IsGif { get; set; } }
[ProtoPackable] internal partial class AlbumVideoInfo { [ProtoMember(1)] public string Id { get; set; } = string.Empty; [ProtoMember(2)] public string Url { get; set; } = string.Empty; [ProtoMember(3)] public AlbumImageInfo? Cover { get; set; } [ProtoMember(4)] public uint Width { get; set; } [ProtoMember(5)] public uint Height { get; set; } [ProtoMember(6)] public ulong VideoTime { get; set; } [ProtoMember(7)] public List<AlbumPhotoUrl> VideoUrl { get; set; } = []; }
[ProtoPackable] internal partial class AlbumMediaInfo { [ProtoMember(1)] public uint Type { get; set; } [ProtoMember(2)] public AlbumImageInfo? Image { get; set; } [ProtoMember(3)] public AlbumVideoInfo? Video { get; set; } [ProtoMember(6)] public string Uploader { get; set; } = string.Empty; [ProtoMember(7)] public ulong BatchId { get; set; } [ProtoMember(8)] public ulong UploadTime { get; set; } }
[ProtoPackable] internal partial class GetMediaListRespData { [ProtoMember(3)] public List<AlbumMediaInfo> MediaList { get; set; } = []; [ProtoMember(4)] public string PrevAttachInfo { get; set; } = string.Empty; [ProtoMember(5)] public string NextAttachInfo { get; set; } = string.Empty; }
[ProtoPackable] internal partial class GetMediaListResponse { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(4)] public GetMediaListRespData? Data { get; set; } }
[ProtoPackable] internal partial class AlbumLikeInfo { [ProtoMember(1)] public string Id { get; set; } = string.Empty; [ProtoMember(3)] public uint Status { get; set; } }
[ProtoPackable] internal partial class AlbumLikeCellCommon { [ProtoMember(3)] public ulong Time { get; set; } [ProtoMember(4)] public string FeedId { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumLikeUser { [ProtoMember(13)] public string Uin { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumLikeUserInfo { [ProtoMember(1)] public AlbumLikeUser User { get; set; } = new(); }
[ProtoPackable] internal partial class AlbumLikeMedia { [ProtoMember(3)] public string AlbumId { get; set; } = string.Empty; [ProtoMember(5)] public ulong BatchId { get; set; } }
[ProtoPackable] internal partial class AlbumLikeQun { [ProtoMember(1)] public string QunId { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumLikePublish { [ProtoMember(1)] public AlbumLikeCellCommon CellCommon { get; set; } = new(); [ProtoMember(2)] public AlbumLikeUserInfo CellUserInfo { get; set; } = new(); [ProtoMember(5)] public AlbumLikeMedia CellMedia { get; set; } = new(); [ProtoMember(12)] public AlbumLikeQun CellQunInfo { get; set; } = new(); }
[ProtoPackable] internal partial class AlbumLikeBody { [ProtoMember(2)] public uint Type { get; set; } [ProtoMember(3)] public AlbumLikeInfo Like { get; set; } = new(); [ProtoMember(4)] public AlbumLikePublish Publish { get; set; } = new(); [ProtoMember(5)] public string ClientKey { get; set; } = string.Empty; }
[ProtoPackable] internal partial class DoQunLikeRequest { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(2)] public string Field2 { get; set; } = string.Empty; [ProtoMember(3)] public string Field3 { get; set; } = string.Empty; [ProtoMember(4)] public AlbumLikeBody Body { get; set; } = new(); [ProtoMember(10)] public List<AlbumExtMapEntry> ExtMap { get; set; } = []; }
[ProtoPackable] internal partial class DoQunLikeResponseBody { [ProtoMember(2)] public AlbumLikeInfo? Like { get; set; } }
[ProtoPackable] internal partial class DoQunLikeResponse { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(4)] public DoQunLikeResponseBody? Body { get; set; } }
[ProtoPackable] internal partial class DeleteMediasReqBody { [ProtoMember(1)] public string GroupId { get; set; } = string.Empty; [ProtoMember(2)] public string AlbumId { get; set; } = string.Empty; [ProtoMember(3)] public List<string> MediaIds { get; set; } = []; [ProtoMember(4)] public List<string> BatchIds { get; set; } = []; }
[ProtoPackable] internal partial class DeleteMediasRequest { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(2)] public string Field2 { get; set; } = string.Empty; [ProtoMember(3)] public string Field3 { get; set; } = string.Empty; [ProtoMember(4)] public DeleteMediasReqBody Body { get; set; } = new(); [ProtoMember(5)] public string TraceId { get; set; } = string.Empty; [ProtoMember(10)] public List<AlbumExtMapEntry> ExtMap { get; set; } = []; }
[ProtoPackable] internal partial class DeleteMediasResponse { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(2)] public int Field2 { get; set; } [ProtoMember(3)] public string? Field3 { get; set; } }
[ProtoPackable] internal partial class AlbumCommentUser { [ProtoMember(13)] public string Uin { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumCommentHeader { [ProtoMember(3)] public uint Field3 { get; set; } [ProtoMember(4)] public string Field4 { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumCommentUserWrap { [ProtoMember(1)] public AlbumCommentUser User { get; set; } = new(); }
[ProtoPackable] internal partial class AlbumCommentPhotoMeta { [ProtoMember(1)] public uint Field1 { get; set; } [ProtoMember(2)] public string Field2 { get; set; } = string.Empty; [ProtoMember(3)] public string Lloc { get; set; } = string.Empty; [ProtoMember(4)] public string Field4 { get; set; } = string.Empty; [ProtoMember(6)] public string Field6 { get; set; } = string.Empty; [ProtoMember(7)] public uint Field7 { get; set; } [ProtoMember(8)] public uint Field8 { get; set; } [ProtoMember(9)] public uint Field9 { get; set; } [ProtoMember(14)] public uint Field14 { get; set; } [ProtoMember(15)] public uint Field15 { get; set; } [ProtoMember(17)] public uint Field17 { get; set; } }
[ProtoPackable] internal partial class AlbumCommentPhotoWrap { [ProtoMember(2)] public AlbumCommentPhotoMeta Meta { get; set; } = new(); }
[ProtoPackable] internal partial class AlbumCommentPhotoInfo { [ProtoMember(1)] public AlbumCommentPhotoWrap Wrap { get; set; } = new(); [ProtoMember(3)] public string AlbumId { get; set; } = string.Empty; [ProtoMember(5)] public uint Field5 { get; set; } }
[ProtoPackable] internal partial class AlbumCommentReqBody { [ProtoMember(1)] public AlbumCommentHeader Header { get; set; } = new(); [ProtoMember(2)] public AlbumCommentUserWrap UserWrap { get; set; } = new(); [ProtoMember(5)] public AlbumCommentPhotoInfo PhotoInfo { get; set; } = new(); }
[ProtoPackable] internal partial class AlbumCommentContentMeta { [ProtoMember(1)] public uint Field1 { get; set; } [ProtoMember(2)] public string Content { get; set; } = string.Empty; [ProtoMember(3)] public string Field3 { get; set; } = string.Empty; [ProtoMember(4)] public string Field4 { get; set; } = string.Empty; [ProtoMember(5)] public uint Field5 { get; set; } [ProtoMember(6)] public string Field6 { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumCommentContent { [ProtoMember(2)] public AlbumCommentUser User { get; set; } = new(); [ProtoMember(3)] public AlbumCommentContentMeta Meta { get; set; } = new(); [ProtoMember(7)] public string ClientKey { get; set; } = string.Empty; }
[ProtoPackable] internal partial class DoQunCommentBody { [ProtoMember(2)] public string GroupId { get; set; } = string.Empty; [ProtoMember(3)] public uint Field3 { get; set; } [ProtoMember(4)] public AlbumCommentReqBody ReqBody { get; set; } = new(); [ProtoMember(5)] public AlbumCommentContent Content { get; set; } = new(); }
[ProtoPackable] internal partial class DoQunCommentRequest { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(2)] public byte[] Field2 { get; set; } = []; [ProtoMember(3)] public byte[] Field3 { get; set; } = []; [ProtoMember(4)] public DoQunCommentBody Body { get; set; } = new(); [ProtoMember(5)] public string TraceId { get; set; } = string.Empty; [ProtoMember(10)] public List<AlbumExtMapEntry> ExtMap { get; set; } = []; }
[ProtoPackable] internal partial class AlbumCommentResponseUser { [ProtoMember(13)] public string Uin { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumCommentResponseContent { [ProtoMember(1)] public uint Type { get; set; } [ProtoMember(2)] public string Content { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumCommentResponseData { [ProtoMember(1)] public string Id { get; set; } = string.Empty; [ProtoMember(2)] public AlbumCommentResponseUser? User { get; set; } [ProtoMember(3)] public List<AlbumCommentResponseContent> Content { get; set; } = []; [ProtoMember(4)] public ulong Time { get; set; } [ProtoMember(7)] public string ClientKey { get; set; } = string.Empty; }
[ProtoPackable] internal partial class AlbumCommentResponseWrap { [ProtoMember(2)] public AlbumCommentResponseData? Data { get; set; } }
[ProtoPackable] internal partial class DoQunCommentResponse { [ProtoMember(1)] public int Field1 { get; set; } [ProtoMember(4)] public AlbumCommentResponseWrap? Comment { get; set; } }
