using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace Lagrange.Proto.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class JceSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Lagrange.Proto.JcePackableAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => EmitType((ClassDeclarationSyntax)ctx.TargetNode, ctx.SemanticModel));
        context.RegisterSourceOutput(types, static (spc, source) => spc.AddSource(source.HintName, source.Text));
    }

    private static GeneratedType EmitType(ClassDeclarationSyntax syntax, SemanticModel model)
    {
        var symbol = (INamedTypeSymbol)model.GetDeclaredSymbol(syntax)!;
        var ns = symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString();
        var fields = new List<(int Tag, string Name, string Type)>();
        foreach (var member in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            var attr = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Lagrange.Proto.JceMemberAttribute");
            if (attr is null || attr.ConstructorArguments.Length == 0) continue;
            fields.Add(((int)attr.ConstructorArguments[0].Value!, member.Name, member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        }
        foreach (var member in symbol.GetMembers().OfType<IFieldSymbol>())
        {
            var attr = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Lagrange.Proto.JceMemberAttribute");
            if (attr is null || attr.ConstructorArguments.Length == 0) continue;
            fields.Add(((int)attr.ConstructorArguments[0].Value!, member.Name, member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        }
        fields.Sort((a, b) => a.Tag.CompareTo(b.Tag));
        var sb = new StringBuilder("// <auto-generated/>\n#nullable enable\nusing global::Lagrange.Proto.Primitives;\n");
        if (ns is not null) sb.Append("namespace ").Append(ns).Append(";\n");
        sb.Append("partial class ").Append(symbol.Name).Append(" : global::Lagrange.Proto.Primitives.IJcePackable<").Append(symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">\n{\n");
        sb.Append("    public static ").Append(symbol.Name).Append(" Parse(ref JceReader reader)\n    {\n        var value = new ").Append(symbol.Name).Append("();\n");
        foreach (var f in fields) sb.Append("        value.").Append(f.Name).Append(" = ").Append(ReadExpression(f.Type, f.Tag)).Append(";\n");
        sb.Append("        return value;\n    }\n}\n");
        return new GeneratedType($"{symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "").Replace('<','_').Replace('>','_')}.Jce.g.cs", sb.ToString());
    }

    private static string ReadExpression(string type, int tag) => type switch
    {
        "global::System.Byte" or "byte" => $"reader.ReadByte({tag})",
        "global::System.SByte" or "sbyte" => $"unchecked((sbyte)reader.ReadByte({tag}))",
        "global::System.Int16" or "short" => $"reader.ReadInt16({tag})",
        "global::System.Int32" or "int" => $"reader.ReadInt32({tag})",
        "global::System.Int64" or "long" => $"reader.ReadInt64({tag})",
        "global::System.String" or "string" => $"reader.ReadString({tag})",
        "global::System.Byte[]" or "byte[]" => $"reader.ReadBytes({tag})",
        _ when type.IndexOf("Dictionary<string, global::System.Collections.Generic.Dictionary<string, byte[]>>", StringComparison.Ordinal) >= 0 => $"reader.ReadNestedByteMap({tag})",
        _ when type.EndsWith("[]", StringComparison.Ordinal) => $"reader.ReadStructList<{type.Substring(0, type.Length - 2)}>({tag})",
        _ when type.EndsWith("?", StringComparison.Ordinal) => $"reader.ReadStruct<{type.Substring(0, type.Length - 1)}>({tag})",
        _ => $"reader.ReadStruct<{type}>({tag})"
    };

    private sealed class GeneratedType
    {
        public string HintName { get; }
        public string Text { get; }
        public GeneratedType(string hintName, string text) { HintName = hintName; Text = text; }
    }
}
