<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <TargetFramework>net10.0</TargetFramework>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateSerializerContexts>true</GenerateSerializerContexts>
    <SerializerContextOutputPath>Generated\SerializerCtx</SerializerContextOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="Lagrange.Core" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\appsettings.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
    <PackageReference Include="FastEndpoints.Generator" Version="8.3.0" PrivateAssets="all" />
    <PackageReference Include="FastEndpoints.OpenApi" Version="8.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="3.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lagrange.Core\Lagrange.Core.csproj" />
    <ProjectReference Include="..\Lagrange.Milky.Generator\Lagrange.Milky.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" GlobalPropertiesToRemove="PublishAot" />
  </ItemGroup>
</Project>
