using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Lagrange.Core.Common;
using Lagrange.Milky.Api;
using Lagrange.Milky.Api.Handlers.File;
using Lagrange.Milky.Api.Handlers.Friend;
using Lagrange.Milky.Api.Handlers.Group;
using Lagrange.Milky.Api.Handlers.Message;
using Lagrange.Milky.Api.Handlers.Interaction;
using Lagrange.Milky.Api.Handlers.System;
using Lagrange.Milky.Events;
using Lagrange.Milky.Events.Converters;
using Lagrange.Milky.Models.Messages;
using Lagrange.Milky.Models.Segments;
using Lagrange.Milky.Signing;

namespace Lagrange.Milky.Serialization;

public static partial class Serializer
{
    public static string JsonSerialize<T>(T value)
    {
        return JsonSerializer.Serialize(value, typeof(T), JsonContext.Default);
    }
    public static byte[] JsonSerializeToUtf8Bytes<T>(T value)
    {
        return JsonSerializer.SerializeToUtf8Bytes(value, typeof(T), JsonContext.Default);
    }
    public static Task JsonSerializableAsync<T>(Stream stream, T value, CancellationToken ct)
    {
        return JsonSerializer.SerializeAsync(stream, value, typeof(T), JsonContext.Default, ct);
    }

    public static T? JsonDeserialize<T>(string json)
    {
        return (T?)JsonSerializer.Deserialize(json, typeof(T), JsonContext.Default);
    }
    public static ValueTask<T?> JsonDeserializeAsync<T>(Stream stream, CancellationToken ct = default)
    {
        var vt = JsonSerializer.DeserializeAsync(stream, typeof(T), JsonContext.Default, ct);
        return vt.IsCompleted ? ValueTask.FromResult((T?)vt.GetAwaiter().GetResult()) : CastAwait(vt);

        static async ValueTask<T?> CastAwait(ValueTask<object?> vt) => (T?)await vt;
    }
    public static ValueTask<object?> JsonDeserializeAsync(Stream stream, Type type, CancellationToken ct)
    {
        return JsonSerializer.DeserializeAsync(stream, type, JsonContext.Default, ct);
    }

    // Signer
    [JsonSerializable(typeof(BotKeystore))]
    [JsonSerializable(typeof(SecSignRequest))]
    [JsonSerializable(typeof(SignerResponse<SecSignResult>))]
    [JsonSerializable(typeof(AndroidSigner.ResponseRoot<AndroidSigner.SignResponse>))]
    [JsonSerializable(typeof(AndroidSigner.ResponseRoot<string>))]
    // Api
    [JsonSerializable(typeof(MilkyApiResponse))]
    [JsonSerializable(typeof(IncomingForwardedMessage))]
    [JsonSerializable(typeof(Lagrange.Milky.Models.GroupAnnouncement))]
    [JsonSerializable(typeof(Lagrange.Milky.Models.FriendRequest))]
    [JsonSerializable(typeof(Lagrange.Milky.Models.GroupFile))]
    [JsonSerializable(typeof(FaceIncomingSegment))]
    [JsonSerializable(typeof(XmlIncomingSegment))]
    [JsonSerializable(typeof(PokeIncomingSegment))]
    [JsonSerializable(typeof(MarkdownIncomingSegment))]
    [JsonSerializable(typeof(KeyboardIncomingSegment))]
    [JsonSerializable(typeof(SpecialPokeIncomingSegment))]
    [JsonSerializable(typeof(JsonIncomingSegment))]
    [JsonSerializable(typeof(LocationIncomingSegment))]
    [JsonSerializable(typeof(MusicIncomingSegment))]
    [JsonSerializable(typeof(ShareIncomingSegment))]
    [JsonSerializable(typeof(ContactIncomingSegment))]
    [JsonSerializable(typeof(DiceIncomingSegment))]
    [JsonSerializable(typeof(RpsIncomingSegment))]
    [JsonSerializable(typeof(LongMsgIncomingSegment))]
    [JsonSerializable(typeof(StreamIncomingSegment))]
    [JsonSerializable(typeof(BounceFaceIncomingSegment))]
    [JsonSerializable(typeof(GroupReactionIncomingSegment))]
    [JsonSerializable(typeof(IReadOnlyList<GroupReactionItem>), TypeInfoPropertyName = "GroupReactionItems")]
    [JsonSerializable(typeof(GreyTipIncomingSegment))]
    [JsonSerializable(typeof(GreyTipOutgoingSegment))]
    [JsonSerializable(typeof(MarketFaceIncomingSegment))]
    [JsonSerializable(typeof(FaceOutgoingSegment))]
    [JsonSerializable(typeof(MarketFaceOutgoingSegment))]
    [JsonSerializable(typeof(XmlOutgoingSegment))]
    [JsonSerializable(typeof(PokeOutgoingSegment))]
    [JsonSerializable(typeof(MarkdownOutgoingSegment))]
    [JsonSerializable(typeof(KeyboardOutgoingSegment))]
    [JsonSerializable(typeof(SpecialPokeOutgoingSegment))]
    [JsonSerializable(typeof(JsonOutgoingSegment))]
    [JsonSerializable(typeof(LocationOutgoingSegment))]
    [JsonSerializable(typeof(MusicOutgoingSegment))]
    [JsonSerializable(typeof(ShareOutgoingSegment))]
    [JsonSerializable(typeof(ContactOutgoingSegment))]
    [JsonSerializable(typeof(DiceOutgoingSegment))]
    [JsonSerializable(typeof(RpsOutgoingSegment))]
    [JsonSerializable(typeof(LongMsgOutgoingSegment))]
    [JsonSerializable(typeof(StreamOutgoingSegment))]
    [JsonSerializable(typeof(IReadOnlyList<Lagrange.Milky.Models.Messages.IncomingForwardedMessage>), TypeInfoPropertyName = "LongMessageItems")]
    [JsonSerializable(typeof(BounceFaceOutgoingSegment))]
    [JsonSerializable(typeof(GroupReactionOutgoingSegment))]
    [JsonSerializable(typeof(GetLoginInfoHandler.Result), TypeInfoPropertyName = "GetLoginInfoResult")]
    [JsonSerializable(typeof(GetImplInfoHandler.Result), TypeInfoPropertyName = "GetImplInfoResult")]
    [JsonSerializable(typeof(GetGroupSystemMessageHandler.Request), TypeInfoPropertyName = "GetGroupSystemMessageRequest")]
    [JsonSerializable(typeof(GetGroupSystemMessageHandler.Result), TypeInfoPropertyName = "GetGroupSystemMessageResult")]
    [JsonSerializable(typeof(IReadOnlyList<Lagrange.Milky.Models.GroupNotificationBase>), TypeInfoPropertyName = "GetGroupSystemMessages")]
    [JsonSerializable(typeof(GetGroupShutListHandler.Request), TypeInfoPropertyName = "GetGroupShutListRequest")]
    [JsonSerializable(typeof(GetGroupShutListHandler.Result), TypeInfoPropertyName = "GetGroupShutListResult")]
    [JsonSerializable(typeof(GetGroupShutListHandler.Member), TypeInfoPropertyName = "GetGroupShutListMember")]
    [JsonSerializable(typeof(GetDoubtFriendRequestsHandler.Result), TypeInfoPropertyName = "GetDoubtFriendRequestsResult")]
    [JsonSerializable(typeof(GetDoubtFriendRequestsHandler.Item), TypeInfoPropertyName = "GetDoubtFriendRequestsItem")]
    [JsonSerializable(typeof(IReadOnlyList<GetDoubtFriendRequestsHandler.Item>), TypeInfoPropertyName = "GetDoubtFriendRequestsItems")]
    [JsonSerializable(typeof(SetDoubtFriendRequestHandler.Request), TypeInfoPropertyName = "SetDoubtFriendRequestRequest")]
    [JsonSerializable(typeof(GetQidianCorpInfoHandler.Request), TypeInfoPropertyName = "GetQidianCorpInfoRequest")]
    [JsonSerializable(typeof(GetQidianCorpInfoHandler.Result), TypeInfoPropertyName = "GetQidianCorpInfoResult")]
    [JsonSerializable(typeof(GetQidianCorpInfoHandler.Corp), TypeInfoPropertyName = "GetQidianCorpInfoCorp")]
    [JsonSerializable(typeof(SendArkShareHandler.Request), TypeInfoPropertyName = "SendArkShareRequest")]
    [JsonSerializable(typeof(SendArkShareHandler.Result), TypeInfoPropertyName = "SendArkShareResult")]
    [JsonSerializable(typeof(SendTuwenArkHandler.Request), TypeInfoPropertyName = "SendTuwenArkRequest")]
    [JsonSerializable(typeof(SendTuwenArkHandler.Result), TypeInfoPropertyName = "SendTuwenArkResult")]
    [JsonSerializable(typeof(GetUserProfileHandler.Request), TypeInfoPropertyName = "GetUserProfileRequest")]
    [JsonSerializable(typeof(GetUserProfileHandler.Result), TypeInfoPropertyName = "GetUserProfileResult")]
    [JsonSerializable(typeof(GetFriendListHandler.Request), TypeInfoPropertyName = "GetFriendListRequest")]
    [JsonSerializable(typeof(GetFriendListHandler.Result), TypeInfoPropertyName = "GetFriendListResult")]
    [JsonSerializable(typeof(GetFriendInfoHandler.Request), TypeInfoPropertyName = "GetFriendInfoRequest")]
    [JsonSerializable(typeof(GetFriendInfoHandler.Result), TypeInfoPropertyName = "GetFriendInfoResult")]
    [JsonSerializable(typeof(GetFriendRequestsHandler.Result), TypeInfoPropertyName = "GetFriendRequestsResult")]
    [JsonSerializable(typeof(GetUnidirectionalFriendListHandler.Result), TypeInfoPropertyName = "GetUnidirectionalFriendListResult")]
    [JsonSerializable(typeof(DeleteFriendHandler.Request), TypeInfoPropertyName = "DeleteFriendRequest")]
    [JsonSerializable(typeof(SetFriendRemarkHandler.Request), TypeInfoPropertyName = "SetFriendRemarkRequest")]
    [JsonSerializable(typeof(HandleFriendRequestHandler.Request), TypeInfoPropertyName = "HandleFriendRequestRequest")]
    [JsonSerializable(typeof(SetFriendCategoryHandler.Request), TypeInfoPropertyName = "SetFriendCategoryRequest")]
    [JsonSerializable(typeof(GetGroupListHandler.Request), TypeInfoPropertyName = "GetGroupListRequest")]
    [JsonSerializable(typeof(GetGroupListHandler.Result), TypeInfoPropertyName = "GetGroupListResult")]
    [JsonSerializable(typeof(GetGroupInfoHandler.Request), TypeInfoPropertyName = "GetGroupInfoRequest")]
    [JsonSerializable(typeof(GetGroupInfoHandler.Result), TypeInfoPropertyName = "GetGroupInfoResult")]
    [JsonSerializable(typeof(GetGroupMemberListHandler.Request), TypeInfoPropertyName = "GetGroupMemberListRequest")]
    [JsonSerializable(typeof(GetGroupMemberListHandler.Result), TypeInfoPropertyName = "GetGroupMemberListResult")]
    [JsonSerializable(typeof(GetGroupMemberInfoHandler.Request), TypeInfoPropertyName = "GetGroupMemberInfoRequest")]
    [JsonSerializable(typeof(GetGroupMemberInfoHandler.Result), TypeInfoPropertyName = "GetGroupMemberInfoResult")]
    [JsonSerializable(typeof(SetPeerPinHandler.Request), TypeInfoPropertyName = "SetPeerPinRequest")]
    [JsonSerializable(typeof(SetAvatarHandler.Request), TypeInfoPropertyName = "SetAvatarRequest")]
    [JsonSerializable(typeof(GetGroupExtInfoHandler.Request), TypeInfoPropertyName = "GetGroupExtInfoRequest")]
    [JsonSerializable(typeof(GetGroupExtInfoHandler.Result), TypeInfoPropertyName = "GetGroupExtInfoResult")]
    [JsonSerializable(typeof(SetOnlineStatusHandler.Request), TypeInfoPropertyName = "SetOnlineStatusRequest")]
    [JsonSerializable(typeof(SetDiyOnlineStatusHandler.Request), TypeInfoPropertyName = "SetDiyOnlineStatusRequest")]
    [JsonSerializable(typeof(SetProfileHandler.Request), TypeInfoPropertyName = "SetProfileRequest")]
    [JsonSerializable(typeof(SetSelfLongNickHandler.Request), TypeInfoPropertyName = "SetSelfLongNickRequest")]
    [JsonSerializable(typeof(SetNicknameHandler.Request), TypeInfoPropertyName = "SetNicknameRequest")]
    [JsonSerializable(typeof(SetBioHandler.Request), TypeInfoPropertyName = "SetBioRequest")]
    [JsonSerializable(typeof(SendProfileLikeHandler.Request), TypeInfoPropertyName = "SendProfileLikeRequest")]
    [JsonSerializable(typeof(GetProfileLikeHandler.Request), TypeInfoPropertyName = "GetProfileLikeRequest")]
    [JsonSerializable(typeof(GetProfileLikeHandler.Result), TypeInfoPropertyName = "GetProfileLikeResult")]
    [JsonSerializable(typeof(GetProfileLikeHandler.ProfileLikeUser), TypeInfoPropertyName = "GetProfileLikeUser")]
    [JsonSerializable(typeof(TranslateEnToZhHandler.Request), TypeInfoPropertyName = "TranslateEnToZhRequest")]
    [JsonSerializable(typeof(TranslateEnToZhHandler.Result), TypeInfoPropertyName = "TranslateEnToZhResult")]
    [JsonSerializable(typeof(string[]), TypeInfoPropertyName = "TranslateEnToZhWords")]
    [JsonSerializable(typeof(ImageOcrHandler.Request), TypeInfoPropertyName = "ImageOcrRequest")]
    [JsonSerializable(typeof(ImageOcrHandler.Result), TypeInfoPropertyName = "ImageOcrResult")]
    [JsonSerializable(typeof(ImageOcrHandler.Text), TypeInfoPropertyName = "ImageOcrText")]
    [JsonSerializable(typeof(ImageOcrHandler.Coordinate), TypeInfoPropertyName = "ImageOcrCoordinate")]
    [JsonSerializable(typeof(ImageOcrHandler.Text[]), TypeInfoPropertyName = "ImageOcrTextArray")]
    [JsonSerializable(typeof(ImageOcrHandler.Coordinate[]), TypeInfoPropertyName = "ImageOcrCoordinateArray")]
    [JsonSerializable(typeof(GetCsrfTokenHandler.Result), TypeInfoPropertyName = "GetCsrfTokenResult")]
    [JsonSerializable(typeof(GetCustomFaceListHandler.Result), TypeInfoPropertyName = "GetCustomFaceListResult")]
    [JsonSerializable(typeof(AddCustomFaceHandler.Request), TypeInfoPropertyName = "AddCustomFaceRequest")]
    [JsonSerializable(typeof(AddCustomFaceHandler.Result), TypeInfoPropertyName = "AddCustomFaceResult")]
    [JsonSerializable(typeof(SetGroupAvatarHandler.Request), TypeInfoPropertyName = "SetGroupAvatarRequest")]
    [JsonSerializable(typeof(GetCustomFaceUrlListHandler.Result), TypeInfoPropertyName = "GetCustomFaceUrlListResult")]
    [JsonSerializable(typeof(GetCustomFaceDetailHandler.Request), TypeInfoPropertyName = "GetCustomFaceDetailRequest")]
    [JsonSerializable(typeof(GetCustomFaceDetailHandler.Result), TypeInfoPropertyName = "GetCustomFaceDetailResult")]
    [JsonSerializable(typeof(ModifyCustomFaceHandler.Request), TypeInfoPropertyName = "ModifyCustomFaceRequest")]
    [JsonSerializable(typeof(DeleteCustomFaceHandler.Request), TypeInfoPropertyName = "DeleteCustomFaceRequest")]
    [JsonSerializable(typeof(MoveCustomFaceHandler.Request), TypeInfoPropertyName = "MoveCustomFaceRequest")]
    [JsonSerializable(typeof(GetSystemFacesHandler.Request), TypeInfoPropertyName = "GetSystemFacesRequest")]
    [JsonSerializable(typeof(GetSystemFacesHandler.Result), TypeInfoPropertyName = "GetSystemFacesResult")]
    [JsonSerializable(typeof(SearchSystemFacesHandler.Request), TypeInfoPropertyName = "SearchSystemFacesRequest")]
    [JsonSerializable(typeof(SearchSystemFacesHandler.Result), TypeInfoPropertyName = "SearchSystemFacesResult")]
    [JsonSerializable(typeof(GetCookiesHandler.Request), TypeInfoPropertyName = "GetCookiesRequest")]
    [JsonSerializable(typeof(GetCookiesHandler.Result), TypeInfoPropertyName = "GetCookiesResult")]
    [JsonSerializable(typeof(SendPrivateMessageHandler.Request), TypeInfoPropertyName = "SendPrivateMessageRequest")]
    [JsonSerializable(typeof(SendPrivateMessageHandler.Result), TypeInfoPropertyName = "SendPrivateMessageResult")]
    [JsonSerializable(typeof(SendGroupMessageHandler.Request), TypeInfoPropertyName = "SendGroupMessageRequest")]
    [JsonSerializable(typeof(SendGroupMessageHandler.Result), TypeInfoPropertyName = "SendGroupMessageResult")]
    [JsonSerializable(typeof(RecallPrivateMessageHandler.Request), TypeInfoPropertyName = "RecallPrivateMessageRequest")]
    [JsonSerializable(typeof(RecallGroupMessageHandler.Request), TypeInfoPropertyName = "RecallGroupMessageRequest")]
    [JsonSerializable(typeof(GetMessageHandler.Request), TypeInfoPropertyName = "GetMessageRequest")]
    [JsonSerializable(typeof(GetMessageHandler.Result), TypeInfoPropertyName = "GetMessageResult")]
    [JsonSerializable(typeof(GetHistoryMessagesHandler.Request), TypeInfoPropertyName = "GetHistoryMessagesRequest")]
    [JsonSerializable(typeof(GetHistoryMessagesHandler.Result), TypeInfoPropertyName = "GetHistoryMessagesResult")]
    [JsonSerializable(typeof(GetResourceTempUrlHandler.Request), TypeInfoPropertyName = "GetResourceTempUrlRequest")]
    [JsonSerializable(typeof(GetResourceTempUrlHandler.Result), TypeInfoPropertyName = "GetResourceTempUrlResult")]
    [JsonSerializable(typeof(SendFriendNudgeHandler.Request), TypeInfoPropertyName = "SendFriendNudgeRequest")]
    [JsonSerializable(typeof(SendLikeHandler.Request), TypeInfoPropertyName = "SendLikeRequest")]
    [JsonSerializable(typeof(SetGroupReactionHandler.Request), TypeInfoPropertyName = "SetGroupReactionRequest")]
    [JsonSerializable(typeof(GetEmojiLikesHandler.Request), TypeInfoPropertyName = "GetEmojiLikesRequest")]
    [JsonSerializable(typeof(GetEmojiLikesHandler.Result), TypeInfoPropertyName = "GetEmojiLikesResult")]
    [JsonSerializable(typeof(GetGroupReactionSummaryHandler.Request), TypeInfoPropertyName = "GetGroupReactionSummaryRequest")]
    [JsonSerializable(typeof(GetGroupReactionSummaryHandler.Result), TypeInfoPropertyName = "GetGroupReactionSummaryResult")]
    [JsonSerializable(typeof(SetInputStatusHandler.Request), TypeInfoPropertyName = "SetInputStatusRequest")]
    [JsonSerializable(typeof(SendPokeHandler.Request), TypeInfoPropertyName = "SendPokeRequest")]
    [JsonSerializable(typeof(SetGroupNameHandler.Request), TypeInfoPropertyName = "SetGroupNameRequest")]
    [JsonSerializable(typeof(SetGroupRemarkHandler.Request), TypeInfoPropertyName = "SetGroupRemarkRequest")]
    [JsonSerializable(typeof(SetGroupMemberCardHandler.Request), TypeInfoPropertyName = "SetGroupMemberCardRequest")]
    [JsonSerializable(typeof(SetGroupMemberAdminHandler.Request), TypeInfoPropertyName = "SetGroupMemberAdminRequest")]
    [JsonSerializable(typeof(SetGroupMemberPermissionHandler.Request), TypeInfoPropertyName = "SetGroupMemberPermissionRequest")]
    [JsonSerializable(typeof(SetGroupAddOptionHandler.Request), TypeInfoPropertyName = "SetGroupAddOptionRequest")]
    [JsonSerializable(typeof(SetGroupSearchHandler.Request), TypeInfoPropertyName = "SetGroupSearchRequest")]
    [JsonSerializable(typeof(SetGroupNewMemberHistoryHandler.Request), TypeInfoPropertyName = "SetGroupNewMemberHistoryRequest")]
    [JsonSerializable(typeof(SetGroupInvitePolicyHandler.Request), TypeInfoPropertyName = "SetGroupInvitePolicyRequest")]
    [JsonSerializable(typeof(SetGroupRobotAddOptionHandler.Request), TypeInfoPropertyName = "SetGroupRobotAddOptionRequest")]
    [JsonSerializable(typeof(GetGroupAdminSettingsHandler.Request), TypeInfoPropertyName = "GetGroupAdminSettingsRequest")]
    [JsonSerializable(typeof(GetGroupAdminSettingsHandler.Result), TypeInfoPropertyName = "GetGroupAdminSettingsResult")]
    [JsonSerializable(typeof(GetPeerPinsHandler.Result), TypeInfoPropertyName = "GetPeerPinsResult")]
    [JsonSerializable(typeof(PeerPinChangeEventConverter.Data), TypeInfoPropertyName = "PeerPinChangeEventData")]
    [JsonSerializable(typeof(FriendRemarkChangedEventConverter.Data), TypeInfoPropertyName = "FriendRemarkChangedEventData")]
    [JsonSerializable(typeof(FriendInputStatusEventConverter.Data), TypeInfoPropertyName = "FriendInputStatusEventData")]
    [JsonSerializable(typeof(OnlineDevicesChangedEventConverter.Data), TypeInfoPropertyName = "OnlineDevicesChangedEventData")]
    [JsonSerializable(typeof(OnlineDevicesChangedEventConverter.Device), TypeInfoPropertyName = "OnlineDeviceData")]
    [JsonSerializable(typeof(OnlineDevicesChangedEventConverter.Device[]), TypeInfoPropertyName = "OnlineDeviceDataArray")]
    [JsonSerializable(typeof(FriendProfileLikeEventConverter.Data), TypeInfoPropertyName = "FriendProfileLikeEventData")]
    [JsonSerializable(typeof(GroupSpecialTitleChangeEventConverter.Data), TypeInfoPropertyName = "GroupSpecialTitleChangeEventData")]
    [JsonSerializable(typeof(FriendAddedEventConverter.Data), TypeInfoPropertyName = "FriendAddedEventData")]
    [JsonSerializable(typeof(GroupSelfJoinedEventConverter.Data), TypeInfoPropertyName = "GroupSelfJoinedEventData")]
    [JsonSerializable(typeof(SetGroupMemberSpecialTitleHandler.Request), TypeInfoPropertyName = "SetGroupMemberSpecialTitleRequest")]
    [JsonSerializable(typeof(SetGroupMemberMute.Request), TypeInfoPropertyName = "SetGroupMemberMuteRequest")]
    [JsonSerializable(typeof(SetGroupWholeMuteHandler.Request), TypeInfoPropertyName = "SetGroupWholeMuteRequest")]
    [JsonSerializable(typeof(KickGroupMemberHandler.Request), TypeInfoPropertyName = "KickGroupMemberRequest")]
    [JsonSerializable(typeof(SetGroupEssenceMessageHandler.Request), TypeInfoPropertyName = "SetGroupEssenceMessageRequest")]
    [JsonSerializable(typeof(QuitGroupHandler.Request), TypeInfoPropertyName = "QuitGroupRequest")]
    [JsonSerializable(typeof(TransferGroupHandler.Request), TypeInfoPropertyName = "TransferGroupRequest")]
    [JsonSerializable(typeof(SetGroupTodoHandler.Request), TypeInfoPropertyName = "SetGroupTodoRequest")]
    [JsonSerializable(typeof(GetGroupTodoHandler.Request), TypeInfoPropertyName = "GetGroupTodoRequest")]
    [JsonSerializable(typeof(GetGroupTodoHandler.Result), TypeInfoPropertyName = "GetGroupTodoResult")]
    [JsonSerializable(typeof(CompleteGroupTodoHandler.Request), TypeInfoPropertyName = "CompleteGroupTodoRequest")]
    [JsonSerializable(typeof(CancelGroupTodoHandler.Request), TypeInfoPropertyName = "CancelGroupTodoRequest")]
    [JsonSerializable(typeof(GetGroupAtAllRemainHandler.Request), TypeInfoPropertyName = "GetGroupAtAllRemainRequest")]
    [JsonSerializable(typeof(GetGroupAtAllRemainHandler.Result), TypeInfoPropertyName = "GetGroupAtAllRemainResult")]
    [JsonSerializable(typeof(SendGroupSignHandler.Request), TypeInfoPropertyName = "SendGroupSignRequest")]
    [JsonSerializable(typeof(SendGroupSignHandler.Result), TypeInfoPropertyName = "SendGroupSignResult")]
    [JsonSerializable(typeof(SendGroupMessageReactionHandler.Request), TypeInfoPropertyName = "SendGroupMessageReactionRequest")]
    [JsonSerializable(typeof(SendGroupNudgeHandler.Request), TypeInfoPropertyName = "SendGroupNudgeRequest")]
    [JsonSerializable(typeof(GetGroupNotificationsHandler.Request), TypeInfoPropertyName = "GetGroupNotificationsRequest")]
    [JsonSerializable(typeof(GetGroupNotificationsHandler.Result), TypeInfoPropertyName = "GetGroupNotificationsResult")]
    [JsonSerializable(typeof(AcceptGroupRequestHandler.Request), TypeInfoPropertyName = "AcceptGroupRequestRequest")]
    [JsonSerializable(typeof(RejectGroupRequestHandler.Request), TypeInfoPropertyName = "RejectGroupRequestRequest")]
    [JsonSerializable(typeof(AcceptGroupInvitationHandler.Request), TypeInfoPropertyName = "AcceptGroupInvitationRequest")]
    [JsonSerializable(typeof(RejectGroupInvitationHandler.Request), TypeInfoPropertyName = "RejectGroupInvitationRequest")]
    [JsonSerializable(typeof(UploadPrivateFileHandler.Request), TypeInfoPropertyName = "UploadPrivateFileRequest")]
    [JsonSerializable(typeof(UploadPrivateFileHandler.Result), TypeInfoPropertyName = "UploadPrivateFileResult")]
    [JsonSerializable(typeof(UploadGroupFileHandler.Request), TypeInfoPropertyName = "UploadGroupFileRequest")]
    [JsonSerializable(typeof(UploadGroupFileHandler.Result), TypeInfoPropertyName = "UploadGroupFileResult")]
    [JsonSerializable(typeof(GetGroupFileDownloadUrlHandler.Request), TypeInfoPropertyName = "GetGroupFileDownloadUrlRequest")]
    [JsonSerializable(typeof(GetGroupFileDownloadUrlHandler.Result), TypeInfoPropertyName = "GetGroupFileDownloadUrlResult")]
    [JsonSerializable(typeof(GetGroupFileUrlHandler.Request), TypeInfoPropertyName = "GetGroupFileUrlRequest")]
    [JsonSerializable(typeof(GetGroupFileUrlHandler.Result), TypeInfoPropertyName = "GetGroupFileUrlResult")]
    [JsonSerializable(typeof(GetGroupFileCountHandler.Request), TypeInfoPropertyName = "GetGroupFileCountRequest")]
    [JsonSerializable(typeof(GetGroupFileCountHandler.Result), TypeInfoPropertyName = "GetGroupFileCountResult")]
    [JsonSerializable(typeof(GetGroupFileSpaceHandler.Request), TypeInfoPropertyName = "GetGroupFileSpaceRequest")]
    [JsonSerializable(typeof(GetGroupFileSpaceHandler.Result), TypeInfoPropertyName = "GetGroupFileSpaceResult")]
    [JsonSerializable(typeof(RenameGroupFileHandler.Request), TypeInfoPropertyName = "RenameGroupFileRequest")]
    [JsonSerializable(typeof(PublishGroupFileHandler.Request), TypeInfoPropertyName = "PublishGroupFileRequest")]
    [JsonSerializable(typeof(TransGroupFileHandler.Request), TypeInfoPropertyName = "TransGroupFileRequest")]
    [JsonSerializable(typeof(TransGroupFileHandler.Result), TypeInfoPropertyName = "TransGroupFileResult")]
    [JsonSerializable(typeof(GetFlashFilesetHandler.Request), TypeInfoPropertyName = "GetFlashFilesetRequest")]
    [JsonSerializable(typeof(GetFlashFilesetHandler.Result), TypeInfoPropertyName = "GetFlashFilesetResult")]
    [JsonSerializable(typeof(GetFlashFilesetHandler.FlashFile), TypeInfoPropertyName = "GetFlashFile")]
    [JsonSerializable(typeof(GetFlashFilesetHandler.FlashFile[]), TypeInfoPropertyName = "GetFlashFileArray")]
    [JsonSerializable(typeof(ListFlashFilesetsHandler.Request), TypeInfoPropertyName = "ListFlashFilesetsRequest")]
    [JsonSerializable(typeof(ListFlashFilesetsHandler.Result), TypeInfoPropertyName = "ListFlashFilesetsResult")]
    [JsonSerializable(typeof(ListFlashFilesetsHandler.FlashFile), TypeInfoPropertyName = "ListFlashFile")]
    [JsonSerializable(typeof(ListFlashFilesetsHandler.FlashFile[]), TypeInfoPropertyName = "ListFlashFileArray")]
    [JsonSerializable(typeof(DeleteFlashFileHandler.Request), TypeInfoPropertyName = "DeleteFlashFileRequest")]
    [JsonSerializable(typeof(RenameFlashFileHandler.Request), TypeInfoPropertyName = "RenameFlashFileRequest")]
    [JsonSerializable(typeof(SendFlashMessageHandler.Request), TypeInfoPropertyName = "SendFlashMessageRequest")]
    [JsonSerializable(typeof(GetFlashFileUrlHandler.Request), TypeInfoPropertyName = "GetFlashFileUrlRequest")]
    [JsonSerializable(typeof(GetFlashFileUrlHandler.Result), TypeInfoPropertyName = "GetFlashFileUrlResult")]
    [JsonSerializable(typeof(GetPrivateFileDownloadUrlHandler.Request), TypeInfoPropertyName = "GetPrivateFileDownloadUrlRequest")]
    [JsonSerializable(typeof(GetPrivateFileDownloadUrlHandler.Result), TypeInfoPropertyName = "GetPrivateFileDownloadUrlResult")]
    [JsonSerializable(typeof(GetGroupPttUrlHandler.Request), TypeInfoPropertyName = "GetGroupPttUrlRequest")]
    [JsonSerializable(typeof(GetGroupPttUrlHandler.Result), TypeInfoPropertyName = "GetGroupPttUrlResult")]
    [JsonSerializable(typeof(GetGroupVideoUrlHandler.Request), TypeInfoPropertyName = "GetGroupVideoUrlRequest")]
    [JsonSerializable(typeof(GetGroupVideoUrlHandler.Result), TypeInfoPropertyName = "GetGroupVideoUrlResult")]
    [JsonSerializable(typeof(GetPrivatePttUrlHandler.Request), TypeInfoPropertyName = "GetPrivatePttUrlRequest")]
    [JsonSerializable(typeof(GetPrivatePttUrlHandler.Result), TypeInfoPropertyName = "GetPrivatePttUrlResult")]
    [JsonSerializable(typeof(GetPrivateVideoUrlHandler.Request), TypeInfoPropertyName = "GetPrivateVideoUrlRequest")]
    [JsonSerializable(typeof(GetPrivateVideoUrlHandler.Result), TypeInfoPropertyName = "GetPrivateVideoUrlResult")]
    [JsonSerializable(typeof(GetForwardedMessagesHandler.Request), TypeInfoPropertyName = "GetForwardedMessagesRequest")]
    [JsonSerializable(typeof(GetForwardedMessagesHandler.Result), TypeInfoPropertyName = "GetForwardedMessagesResult")]
    [JsonSerializable(typeof(IncomingForwardedMessage[]), TypeInfoPropertyName = "IncomingForwardedMessageArray")]
    [JsonSerializable(typeof(GetCollectionHandler.Request), TypeInfoPropertyName = "GetCollectionRequest")]
    [JsonSerializable(typeof(GetCollectionHandler.Result), TypeInfoPropertyName = "GetCollectionResult")]
    [JsonSerializable(typeof(GetCollectionHandler.Item), TypeInfoPropertyName = "GetCollectionItem")]
    [JsonSerializable(typeof(GetCollectionHandler.Item[]), TypeInfoPropertyName = "GetCollectionItemArray")]
    [JsonSerializable(typeof(GetGroupAlbumsHandler.Request), TypeInfoPropertyName = "GetGroupAlbumsRequest")]
    [JsonSerializable(typeof(GetGroupAlbumsHandler.Result), TypeInfoPropertyName = "GetGroupAlbumsResult")]
    [JsonSerializable(typeof(GetGroupAlbumsHandler.Album), TypeInfoPropertyName = "GetGroupAlbum")]
    [JsonSerializable(typeof(GetGroupAlbumsHandler.Album[]), TypeInfoPropertyName = "GetGroupAlbumArray")]
    [JsonSerializable(typeof(GetQzoneMessageListHandler.Request), TypeInfoPropertyName = "GetQzoneMessageListRequest")]
    [JsonSerializable(typeof(GetQzoneMessageListHandler.Result), TypeInfoPropertyName = "GetQzoneMessageListResult")]
    [JsonSerializable(typeof(GetQzoneMessageListHandler.Message), TypeInfoPropertyName = "GetQzoneMessage")]
    [JsonSerializable(typeof(GetQzoneMessageListHandler.Message[]), TypeInfoPropertyName = "GetQzoneMessageArray")]
    [JsonSerializable(typeof(GetQzoneFeedsHandler.Request), TypeInfoPropertyName = "GetQzoneFeedsRequest")]
    [JsonSerializable(typeof(GetQzoneFeedsHandler.Result), TypeInfoPropertyName = "GetQzoneFeedsResult")]
    [JsonSerializable(typeof(GetQzoneFeedsHandler.Feed), TypeInfoPropertyName = "GetQzoneFeed")]
    [JsonSerializable(typeof(GetQzoneFeedsHandler.Feed[]), TypeInfoPropertyName = "GetQzoneFeedArray")]
    [JsonSerializable(typeof(UploadQzoneImageHandler.Request), TypeInfoPropertyName = "UploadQzoneImageRequest")]
    [JsonSerializable(typeof(UploadQzoneImageHandler.Result), TypeInfoPropertyName = "UploadQzoneImageResult")]
    [JsonSerializable(typeof(SetQzoneLikeHandler.Request), TypeInfoPropertyName = "SetQzoneLikeRequest")]
    [JsonSerializable(typeof(SetQzoneLikeHandler.Result), TypeInfoPropertyName = "SetQzoneLikeResult")]
    [JsonSerializable(typeof(CommentQzoneMessageHandler.Request), TypeInfoPropertyName = "CommentQzoneMessageRequest")]
    [JsonSerializable(typeof(CommentQzoneMessageHandler.Result), TypeInfoPropertyName = "CommentQzoneMessageResult")]
    [JsonSerializable(typeof(DeleteQzoneMessageHandler.Request), TypeInfoPropertyName = "DeleteQzoneMessageRequest")]
    [JsonSerializable(typeof(PublishQzoneMessageHandler.Request), TypeInfoPropertyName = "PublishQzoneMessageRequest")]
    [JsonSerializable(typeof(PublishQzoneMessageHandler.Result), TypeInfoPropertyName = "PublishQzoneMessageResult")]
    [JsonSerializable(typeof(SetQzoneBlackHandler.Request), TypeInfoPropertyName = "SetQzoneBlackRequest")]
    [JsonSerializable(typeof(GetFriendDressHandler.Request), TypeInfoPropertyName = "GetFriendDressRequest")]
    [JsonSerializable(typeof(GetFriendDressHandler.Result), TypeInfoPropertyName = "GetFriendDressResult")]
    [JsonSerializable(typeof(GetFriendDressHandler.Item), TypeInfoPropertyName = "GetFriendDressItem")]
    [JsonSerializable(typeof(GetFriendDressHandler.Item[]), TypeInfoPropertyName = "GetFriendDressItemArray")]
    [JsonSerializable(typeof(GetGroupEssenceHandler.Request), TypeInfoPropertyName = "GetGroupEssenceRequest")]
    [JsonSerializable(typeof(GetGroupEssenceHandler.Result), TypeInfoPropertyName = "GetGroupEssenceResult")]
    [JsonSerializable(typeof(GetGroupEssenceHandler.Message), TypeInfoPropertyName = "GetGroupEssenceMessage")]
    [JsonSerializable(typeof(GetGroupEssenceHandler.Message[]), TypeInfoPropertyName = "GetGroupEssenceMessageArray")]
    [JsonSerializable(typeof(GetGroupEssenceMessagesHandler.Request), TypeInfoPropertyName = "GetGroupEssenceMessagesRequest")]
    [JsonSerializable(typeof(GetGroupEssenceMessagesHandler.Result), TypeInfoPropertyName = "GetGroupEssenceMessagesResult")]
    [JsonSerializable(typeof(GetGroupEssenceMessagesHandler.Message), TypeInfoPropertyName = "GetGroupEssenceMessagesMessage")]
    [JsonSerializable(typeof(GetGroupEssenceMessagesHandler.Message[]), TypeInfoPropertyName = "GetGroupEssenceMessagesMessageArray")]
    [JsonSerializable(typeof(GetGroupHonorHandler.Request), TypeInfoPropertyName = "GetGroupHonorRequest")]
    [JsonSerializable(typeof(GetGroupHonorHandler.Result), TypeInfoPropertyName = "GetGroupHonorResult")]
    [JsonSerializable(typeof(GetGroupHonorHandler.Item), TypeInfoPropertyName = "GetGroupHonorItem")]
    [JsonSerializable(typeof(GetGroupHonorHandler.Item[]), TypeInfoPropertyName = "GetGroupHonorItemArray")]
    [JsonSerializable(typeof(GetGroupAnnouncementsHandler.Request), TypeInfoPropertyName = "GetGroupAnnouncementsRequest")]
    [JsonSerializable(typeof(GetGroupAnnouncementsHandler.Result), TypeInfoPropertyName = "GetGroupAnnouncementsResult")]
    [JsonSerializable(typeof(GetGroupAnnouncementsHandler.Item), TypeInfoPropertyName = "GetGroupAnnouncementItem")]
    [JsonSerializable(typeof(GetGroupAnnouncementsHandler.Item[]), TypeInfoPropertyName = "GetGroupAnnouncementItemArray")]
    [JsonSerializable(typeof(SendGroupAnnouncementHandler.Request), TypeInfoPropertyName = "SendGroupAnnouncementRequest")]
    [JsonSerializable(typeof(UploadGroupAnnouncementImageHandler.Request), TypeInfoPropertyName = "UploadGroupAnnouncementImageRequest")]
    [JsonSerializable(typeof(UploadGroupAnnouncementImageHandler.Result), TypeInfoPropertyName = "UploadGroupAnnouncementImageResult")]
    [JsonSerializable(typeof(DeleteGroupAnnouncementHandler.Request), TypeInfoPropertyName = "DeleteGroupAnnouncementRequest")]
    [JsonSerializable(typeof(GetGroupSignInHandler.Request), TypeInfoPropertyName = "GetGroupSignInRequest")]
    [JsonSerializable(typeof(GetGroupSignInHandler.Result), TypeInfoPropertyName = "GetGroupSignInResult")]
    [JsonSerializable(typeof(GetGroupSignInHandler.Item), TypeInfoPropertyName = "GetGroupSignInItem")]
    [JsonSerializable(typeof(GetGroupSignInHandler.Item[]), TypeInfoPropertyName = "GetGroupSignInItemArray")]
    [JsonSerializable(typeof(MarkMessageAsReadHandler.Request), TypeInfoPropertyName = "MarkMessageAsReadRequest")]
    [JsonSerializable(typeof(MarkAllMessagesAsReadHandler.Request), TypeInfoPropertyName = "MarkAllMessagesAsReadRequest")]
    [JsonSerializable(typeof(long[]), TypeInfoPropertyName = "MarkAllMessagesReadLongArray")]
    [JsonSerializable(typeof(GetGroupAlbumMediaHandler.Request), TypeInfoPropertyName = "GetGroupAlbumMediaRequest")]
    [JsonSerializable(typeof(GetGroupAlbumMediaHandler.Result), TypeInfoPropertyName = "GetGroupAlbumMediaResult")]
    [JsonSerializable(typeof(GetGroupAlbumMediaHandler.Media), TypeInfoPropertyName = "GetGroupAlbumMedia")]
    [JsonSerializable(typeof(GetGroupAlbumMediaHandler.Media[]), TypeInfoPropertyName = "GetGroupAlbumMediaArray")]
    [JsonSerializable(typeof(UploadGroupAlbumImageHandler.Request), TypeInfoPropertyName = "UploadGroupAlbumImageRequest")]
    [JsonSerializable(typeof(UploadGroupAlbumImageHandler.Result), TypeInfoPropertyName = "UploadGroupAlbumImageResult")]
    [JsonSerializable(typeof(SetGroupAlbumLikeHandler.Request), TypeInfoPropertyName = "SetGroupAlbumLikeRequest")]
    [JsonSerializable(typeof(DeleteGroupAlbumMediaHandler.Request), TypeInfoPropertyName = "DeleteGroupAlbumMediaRequest")]
    [JsonSerializable(typeof(CommentGroupAlbumMediaHandler.Request), TypeInfoPropertyName = "CommentGroupAlbumMediaRequest")]
    [JsonSerializable(typeof(CommentGroupAlbumMediaHandler.Result), TypeInfoPropertyName = "CommentGroupAlbumMediaResult")]
    [JsonSerializable(typeof(CreateFlashTaskHandler.Request), TypeInfoPropertyName = "CreateFlashTaskRequest")]
    [JsonSerializable(typeof(CreateFlashTaskHandler.Result), TypeInfoPropertyName = "CreateFlashTaskResult")]
    [JsonSerializable(typeof(CompleteFlashTaskHandler.Request), TypeInfoPropertyName = "CompleteFlashTaskRequest")]
    [JsonSerializable(typeof(CommitFlashFileHandler.Request), TypeInfoPropertyName = "CommitFlashFileRequest")]
    [JsonSerializable(typeof(SetFlashTaskStatusHandler.Request), TypeInfoPropertyName = "SetFlashTaskStatusRequest")]
    [JsonSerializable(typeof(GetGroupFilesHandler.Request), TypeInfoPropertyName = "GetGroupFilesRequest")]
    [JsonSerializable(typeof(GetGroupFilesHandler.Result), TypeInfoPropertyName = "GetGroupFilesResult")]
    [JsonSerializable(typeof(MoveGroupFileHandler.Request), TypeInfoPropertyName = "MoveGroupFileRequest")]
    [JsonSerializable(typeof(DeleteGroupFileHandler.Request), TypeInfoPropertyName = "DeleteGroupFileRequest")]
    [JsonSerializable(typeof(CreateGroupFolderHandler.Request), TypeInfoPropertyName = "CreateGroupFolderRequest")]
    [JsonSerializable(typeof(CreateGroupFolderHandler.Result), TypeInfoPropertyName = "CreateGroupFolderResult")]
    [JsonSerializable(typeof(RenameGroupFolderHandler.Request), TypeInfoPropertyName = "RenameGroupFolderRequest")]
    [JsonSerializable(typeof(DeleteGroupFolderHandler.Request), TypeInfoPropertyName = "DeleteGroupFolderRequest")]
    // Event
    [JsonSerializable(typeof(MilkyEvent))]
    [JsonSerializable(typeof(BotOfflineEventConverter.Data), TypeInfoPropertyName = "BotOfflineEventData")]
    [JsonSerializable(typeof(MessageRecallEventConverter.Data), TypeInfoPropertyName = "MessageRecallEventData")]
    [JsonSerializable(typeof(FriendRequestEventConverter.Data), TypeInfoPropertyName = "FriendRequestEventData")]
    [JsonSerializable(typeof(GroupJoinRequestEventConverter.Data), TypeInfoPropertyName = "GroupJoinRequestEventData")]
    [JsonSerializable(typeof(GroupInvitedJoinRequestEventConverter.Data), TypeInfoPropertyName = "GroupInvitedJoinRequestEventData")]
    [JsonSerializable(typeof(GroupInvitationEventConverter.Data), TypeInfoPropertyName = "GroupInvitationEventData")]
    [JsonSerializable(typeof(GroupMemberIncreaseEventConverter.Data), TypeInfoPropertyName = "GroupMemberIncreaseEventData")]
    [JsonSerializable(typeof(GroupMemberDecreaseEventConverter.Data), TypeInfoPropertyName = "GroupMemberDecreaseEventData")]
    [JsonSerializable(typeof(GroupMessageReactionEventConverter.Data), TypeInfoPropertyName = "GroupMessageReactionEventData")]
    [JsonSerializable(typeof(GroupNudgeEventConverter.Data), TypeInfoPropertyName = "GroupNudgeEventData")]
    [JsonSerializable(typeof(FriendNudgeEventConverter.Data), TypeInfoPropertyName = "FriendNudgeEventData")]
    [JsonSerializable(typeof(FriendFileUploadEventConverter.Data), TypeInfoPropertyName = "FriendFileUploadEventData")]
    [JsonSerializable(typeof(GroupAdminEventConverter.Data), TypeInfoPropertyName = "GroupAdminEventData")]
    [JsonSerializable(typeof(GroupEssenceEventConverter.Data), TypeInfoPropertyName = "GroupEssenceEventData")]
    [JsonSerializable(typeof(GroupFileUploadEventConverter.Data), TypeInfoPropertyName = "GroupFileUploadEventData")]
    [JsonSerializable(typeof(GroupMuteEventConverter.Data), TypeInfoPropertyName = "GroupMuteEventData")]
    [JsonSerializable(typeof(GroupNameChangeEventConverter.Data), TypeInfoPropertyName = "GroupNameChangeEventData")]
    private sealed partial class JsonContext : JsonSerializerContext;
}
